import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Montserrat, Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const idGrotesk = localFont({
  src: [{ path: "../public/font/IDGrotesk-Regular.ttf", weight: "400" }],
  variable: "--font-id",
});

const benzGrotesk = localFont({
  src: [
    { path: "../public/font/Benz-Grotesk.ttf", weight: "400" },
  ],
  variable: "--font-benz",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-spacegrotesk",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${spaceGrotesk.variable} ${geistMono.variable} ${montserrat.variable} ${idGrotesk.variable} ${benzGrotesk.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><Providers>{children}</Providers></body>
    </html>
  );
}
