import type { Metadata } from "next";
import Script from "next/script";
import {
  Geist,
  Geist_Mono,
  Inter,
  Montserrat,
  Space_Grotesk,
  DM_Serif_Display,
} from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import Providers from "@/components/Providers";
import SocketAnnouncer from "@/components/SocketAnnouncer";
import { getUser } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const idGrotesk = localFont({
  src: [{ path: "../public/font/IDGrotesk-Regular.ttf", weight: "400" }],
  variable: "--font-id",
});

const benzGrotesk = localFont({
  src: [{ path: "../public/font/Benz-Grotesk.ttf", weight: "400" }],
  variable: "--font-benz",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-spacegrotesk",
  subsets: ["latin"],
});

const dmSerif = DM_Serif_Display({
  variable: "--font-dmserif",
  weight: ["400"],
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "TECH ENGI",
  description: "Generated by Arinova Studio",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getUser();

  return (
    <html lang="en" className="h-full antialiased">
      <body
        className={`min-h-full flex flex-col ${geistSans.variable} ${spaceGrotesk.variable} ${geistMono.variable} ${montserrat.variable} ${idGrotesk.variable} ${benzGrotesk.variable} ${inter.variable} ${dmSerif.variable}`}
      >
        {/* Facebook Meta Pixel */}
        <Script id="facebook-pixel" strategy="afterInteractive">
          {`
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}
            (window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');

            fbq('init', '888842877025528');
            fbq('track', 'PageView');
          `}
        </Script>

        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=888842877025528&ev=PageView&noscript=1"
            alt=""
          />
        </noscript>

        <SocketAnnouncer userId={user?.id} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}